name = "sitio-coches-api"
main = "workers/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "sitio-coches-api"

[[d1_databases]]
binding = "DB"
database_name = "sitio-coches"
database_id = "your-database-id"

[vars]
ENVIRONMENT = "production"